export const products = [
  {
    id: 1,
    name: "Wireless Headphones",
    slug: "wireless-headphones",
    price: 450000,
    stock: 12,
    category: 1,
    category_name: "Electronics",
    rating: 4,
    img: "./images/Headphones.jpg",
  },
  {
    id: 2,
    name: "Smart Watch",
    slug: "smart-watch",
    price: 650000,
    stock: 8,
    category: 1,
    category_name: "Electronics",
    rating: 5,
    img: "./images/Smartwatch.jpg",
  },
  {
    id: 3,
    name: "Laptop Gaming",
    slug: "laptop-gaming",
    price: 12500000,
    stock: 5,
    category: 1,
    category_name: "Electronics",
    rating: 4,
    img: "./images/Laptop-Gaming.jpg",
  },
  {
    id: 4,
    name: "Smartphone",
    slug: "smartphone",
    price: 3500000,
    stock: 15,
    category: 1,
    category_name: "Electronics",
    rating: 4,
    img: "./images/Smartphone.jpg",
  },
  {
    id: 5,
    name: "Kaos Polos Cotton",
    slug: "kaos-polos-cotton",
    price: 85000,
    stock: 50,
    category: 2,
    category_name: "Fashion",
    rating: 3,
    img: "./images/Kaos-Polos.jpg",
  },
  {
    id: 6,
    name: "Sepatu Sneakers Sport",
    slug: "sepatu-sneakers-sport",
    price: 250000,
    stock: 20,
    category: 2,
    category_name: "Fashion",
    rating: 4,
    img: "./images/Sneakers.jpg",
  }
];